REPORT ZPRG_ALV2.

TABLES: VBAK, VBAP, SSCRFIELDS.

* Extracted from project report (core program structure)

TYPES: BEGIN OF VBAK_TYPE,
         VBELN TYPE VBAK-VBELN,
         TRVOG TYPE VBAK-TRVOG,
         KTEXT TYPE VBAK-KTEXT,
         AUART TYPE VBAK-AUART,
         KUNNR TYPE VBAK-KUNNR,
         ERDAT TYPE VBAK-ERDAT,
         AUDAT TYPE VBAK-AUDAT,
         BSTNK TYPE VBAK-BSTNK,
         ERNAM TYPE VBAK-ERNAM,
         VKORG TYPE VBAK-VKORG,
         VTWEG TYPE VBAK-VTWEG,
         SPART TYPE VBAK-SPART,
         VKGRP TYPE VBAK-VKGRP,
         VKBUR TYPE VBAK-VKBUR,
         WAERK TYPE VBAK-WAERK,
         NETWR TYPE VBAK-NETWR,
         AWAHR TYPE VBAK-AWAHR,
         GUEBG TYPE VBAK-GUEBG,
         GUEEN TYPE VBAK-GUEEN,
       END OF VBAK_TYPE.

START-OF-SELECTION.
  WRITE: / 'Quotation Assistance Tool - ALV Project'.
